apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth

resources:
- github.com/kubeflow/manifests/common/dex/overlays/istio?ref=v1.10-branch

patchesStrategicMerge:
- configmap-patch.yaml
